/**
 * This file was generated by scripts/generate-types.mjs. Do not edit.
 * Source swagger SHA-256: 960f8629333a3f09cac00abc7fc8fb7d68c165cac7a216639e536d9c6af24c04
 */

import type {
  Attachment,
  AttachmentFileUrl,
  CalendarEvents,
  CommentActivity,
  CustomField,
  HomeTasks,
  List,
  ListEnumerate,
  Meeting,
  MeetingDetail,
  MeetingRecordingResource,
  Meetings,
  Note,
  NoteDetail,
  Notes,
  Notifications,
  ReactionReadOnly,
  Search,
  SearchDetail,
  SearchResults,
  Searches,
  SubList,
  Tag,
  Task,
  TaskActivities,
  TaskBulkUpdateResult,
  TokenDetails,
  User,
  UserDetail,
  UserDetailWithTeam,
  UserResource,
  Workflow,
  WorkflowDetail,
  Workflows,
} from './generated.js';

export const attachment: Attachment = {
  "id": "6a844d3965f82309911408ca",
  "title": {
    "text": "Ship v3"
  },
  "createdAt": "2026-08-18T12:16:57.347Z",
  "updatedAt": "2026-08-18T12:16:57.347Z",
  "user": {
    "id": "4214932441cb21eebdb396bfe34a8340",
    "name": "Grace Hopper",
    "userName": "grace",
    "avatar": "https://cdn.workast.io/avatar.png",
    "platformDetails": {
      "name": "slack",
      "imChannel": "D3EEXS3J6",
      "selfChannel": "D1HN843U3",
      "userId": "U0HBQESA1",
      "teamId": "T0HBUA0TC"
    }
  },
  "app": {
    "id": "5d9a6b09269e415d36380d23",
    "name": "Example App",
    "description": "Ship v3",
    "icon": "https://cdn.workast.io/avatar.png",
    "createdAt": "2019-10-06T22:30:33.687Z",
    "updatedAt": "2020-03-06T21:14:00.371Z",
    "clientId": "S4GuidJp6frYrxLTuQBM5JoTug",
    "accessType": "user",
    "developedByWorkast": true
  },
  "author": {
    "id": "4214932441cb21eebdb396bfe34a8340",
    "name": "Grace Hopper",
    "userName": "grace",
    "email": "grace@example.com",
    "platformDetails": {
      "name": "slack",
      "imChannel": "D3EEXS3J6",
      "selfChannel": "D1HN843U3",
      "userId": "U0HBQESA1",
      "teamId": "T0HBUA0TC"
    },
    "confirmed": true,
    "avatar": "https://cdn.workast.io/avatar.png",
    "costCenter": "5c1b92b0a57d2b342c1a610e"
  }
};

export const attachmentFileUrl: AttachmentFileUrl = {
  "id": "6a844fd765f8230991142151",
  "createdAt": "2026-08-18T12:28:07.685Z",
  "updatedAt": "2026-08-18T12:28:09.193Z",
  "user": {
    "id": "4214932441cb21eebdb396bfe34a8340",
    "virtualId": "c2xhY2svL1QwSEJVQTBUQzpVMEhCUUVTQTE=",
    "name": "Grace Hopper",
    "userName": "grace",
    "avatar": "https://cdn.workast.io/avatar.png",
    "platformDetails": {
      "name": "slack",
      "imChannel": "D3EEXS3J6",
      "selfChannel": "D1HN843U3",
      "userId": "U0HBQESA1",
      "teamId": "T0HBUA0TC"
    }
  },
  "file": {
    "name": "avatar.png",
    "type": "image/png",
    "size": 17101,
    "url": "/files/5dc40cff038a590f79c403c0/b9ca2e09-12e8-4c34-99dd-10dfaf345660",
    "thumbnails": {
      "250": "https://example.com/file",
      "500": "https://example.com/file"
    }
  },
  "link": "https://example.com/file",
  "fileUrl": "https://example.com/file"
};

export const calendarEvents: CalendarEvents = {
  "events": [
    {
      "busy": true,
      "calendarId": "grace@example.com",
      "createdAt": 1781850701,
      "icalUid": "3b5ei15dmlrh6et2aqf7q07hbk@example.com",
      "id": "3b5ei15dmlrh6et2aqf7q07hbk",
      "organizer": {
        "email": "grace@example.com",
        "name": "Grace Hopper"
      },
      "participants": [],
      "readOnly": false,
      "status": "confirmed",
      "title": "Standup",
      "updatedAt": 1782098660,
      "visibility": "default",
      "when": {
        "endDate": "2026-07-18",
        "object": "datespan",
        "startDate": "2026-06-27"
      },
      "meeting": null
    }
  ]
};

export const commentActivity: CommentActivity = {
  "id": "686f7912fc2fef09733c6f58",
  "type": "comment",
  "value": "Standup",
  "status": "active",
  "createdAt": "2025-07-10T08:25:54.274Z",
  "updatedAt": "2025-07-10T08:25:54.274Z",
  "mentions": [
    {
      "id": "b2956627fe26a2c1e4b6d5202413f779",
      "name": "Ada Lovelace",
      "userName": "ada",
      "email": "ada@example.com",
      "platformDetails": {
        "name": "slack",
        "imChannel": "D3F5RQA6B",
        "selfChannel": "D1LGYBCFQ",
        "userId": "U0JU26WRG",
        "teamId": "T0HBUA0TC"
      },
      "confirmed": true,
      "avatar": "https://cdn.workast.io/avatar.png",
      "costCenter": "5c1b92b0a57d2b342c1a610e"
    }
  ],
  "reactions": [],
  "actor": {
    "type": "User",
    "data": {
      "id": "4214932441cb21eebdb396bfe34a8340",
      "name": "Grace Hopper",
      "userName": "grace",
      "email": "grace@example.com",
      "platformDetails": {
        "name": "slack",
        "imChannel": "D3EEXS3J6",
        "selfChannel": "D1HN843U3",
        "userId": "U0HBQESA1",
        "teamId": "T0HBUA0TC"
      },
      "confirmed": true,
      "avatar": "https://cdn.workast.io/avatar.png",
      "costCenter": "5c1b92b0a57d2b342c1a610e"
    }
  }
};

export const customField: CustomField = {
  "id": "61a50f7ed892d94d8c9d285e",
  "name": "Priority",
  "description": "Ship v3",
  "type": "options",
  "useAsTaskColor": false,
  "options": [
    {
      "id": "61a50f7ed892d94d8c9d285f",
      "name": "Low",
      "color": "#F2994A"
    },
    {
      "id": "63ec2019d467b10e1de14f02",
      "name": "Medium",
      "color": "#20e48b"
    },
    {
      "id": "63ec2019d467b10e1de14f03",
      "name": "Normal",
      "color": "#1156ff"
    },
    {
      "id": "63ec2019d467b10e1de14f04",
      "name": "High",
      "color": "#f50c0c"
    }
  ]
};

export const homeTasks: HomeTasks = {
  "tasks": [
    {
      "status": "pending",
      "text": "Ship v3",
      "shortId": "T4GNY",
      "createdAt": "2022-01-10T12:12:46.308Z",
      "updatedAt": "2025-07-10T08:25:54.460Z",
      "listPosition": 99999,
      "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49/task/3634dc043f0d415ec2d307284a3cfe69",
      "calendars": [
        "b2956627fe26a2c1e4b6d5202413f779"
      ],
      "id": "3634dc043f0d415ec2d307284a3cfe69",
      "list": {
        "id": "603449f6f107b67c63e8cee9",
        "name": "Product",
        "type": "group",
        "privacy": "private",
        "subLists": [
          {
            "id": "603449f6f107b67c63e8cee8",
            "name": "To-do",
            "listPosition": 100000,
            "createdBy": "4214932441cb21eebdb396bfe34a8340"
          },
          {
            "id": "610ffd8c7374d6331a4178d8",
            "name": "In Progress",
            "listPosition": 700000,
            "createdBy": "4214932441cb21eebdb396bfe34a8340"
          }
        ],
        "link": "https://app.workast.com/list/603449f6f107b67c63e8cee9"
      },
      "listId": "603449f6f107b67c63e8cee9",
      "subListId": "610ffd8c7374d6331a4178d8",
      "subList": {
        "id": "610ffd8c7374d6331a4178d8",
        "name": "To-do"
      },
      "assignedTo": [
        {
          "id": "b2956627fe26a2c1e4b6d5202413f779",
          "name": "Ada Lovelace",
          "userName": "ada",
          "email": "ada@example.com",
          "platformDetails": {
            "name": "slack",
            "imChannel": "D3F5RQA6B",
            "selfChannel": "D1LGYBCFQ",
            "userId": "U0JU26WRG",
            "teamId": "T0HBUA0TC"
          },
          "confirmed": true,
          "avatar": "https://cdn.workast.io/avatar.png",
          "costCenter": "5c1b92b0a57d2b342c1a610e"
        }
      ],
      "subscribers": [
        {
          "id": "b2956627fe26a2c1e4b6d5202413f779",
          "name": "Ada Lovelace",
          "userName": "ada",
          "email": "ada@example.com",
          "platformDetails": {
            "name": "slack",
            "imChannel": "D3F5RQA6B",
            "selfChannel": "D1LGYBCFQ",
            "userId": "U0JU26WRG",
            "teamId": "T0HBUA0TC"
          },
          "confirmed": true,
          "avatar": "https://cdn.workast.io/avatar.png",
          "costCenter": "5c1b92b0a57d2b342c1a610e"
        },
        {
          "id": "4214932441cb21eebdb396bfe34a8340",
          "name": "Grace Hopper",
          "userName": "grace",
          "email": "grace@example.com",
          "platformDetails": {
            "name": "slack",
            "imChannel": "D3EEXS3J6",
            "selfChannel": "D1HN843U3",
            "userId": "U0HBQESA1",
            "teamId": "T0HBUA0TC"
          },
          "confirmed": true,
          "avatar": "https://cdn.workast.io/avatar.png",
          "costCenter": "5c1b92b0a57d2b342c1a610e"
        }
      ],
      "allDay": false,
      "createdBy": {
        "id": "b2956627fe26a2c1e4b6d5202413f779",
        "name": "Ada Lovelace",
        "userName": "ada",
        "email": "ada@example.com",
        "platformDetails": {
          "name": "slack",
          "imChannel": "D3F5RQA6B",
          "selfChannel": "D1LGYBCFQ",
          "userId": "U0JU26WRG",
          "teamId": "T0HBUA0TC"
        },
        "confirmed": true,
        "avatar": "https://cdn.workast.io/avatar.png",
        "costCenter": "5c1b92b0a57d2b342c1a610e"
      },
      "hasDescription": true,
      "numberOfComments": 1,
      "numberOfAttachments": 0,
      "totalSubTasks": 1,
      "completedSubTasks": 0,
      "isSubscribed": true,
      "lastComment": {
        "id": "686f7912fc2fef09733c6f58",
        "type": "comment",
        "value": "Standup",
        "status": "active",
        "createdAt": "2025-07-10T08:25:54.274Z",
        "updatedAt": "2025-07-10T08:25:54.274Z",
        "mentions": [
          {
            "id": "b2956627fe26a2c1e4b6d5202413f779",
            "name": "Ada Lovelace",
            "userName": "ada",
            "email": "ada@example.com",
            "platformDetails": {
              "name": "slack",
              "imChannel": "D3F5RQA6B",
              "selfChannel": "D1LGYBCFQ",
              "userId": "U0JU26WRG",
              "teamId": "T0HBUA0TC"
            },
            "confirmed": true,
            "avatar": "https://cdn.workast.io/avatar.png",
            "costCenter": "5c1b92b0a57d2b342c1a610e"
          }
        ],
        "reactions": [],
        "actor": {
          "type": "User",
          "data": {
            "id": "4214932441cb21eebdb396bfe34a8340",
            "name": "Grace Hopper",
            "userName": "grace",
            "email": "grace@example.com",
            "platformDetails": {
              "name": "slack",
              "imChannel": "D3EEXS3J6",
              "selfChannel": "D1HN843U3",
              "userId": "U0HBQESA1",
              "teamId": "T0HBUA0TC"
            },
            "confirmed": true,
            "avatar": "https://cdn.workast.io/avatar.png",
            "costCenter": "5c1b92b0a57d2b342c1a610e"
          }
        }
      },
      "taskStatus": {
        "id": "5c7184fa40721e2ed4175a6e",
        "label": "Open",
        "color": "#808080",
        "createdAt": "2019-02-23T17:38:02.928Z",
        "updatedAt": "2019-02-23T17:38:02.928Z"
      },
      "milestones": [],
      "inHome": true,
      "fields": []
    }
  ],
  "total": 1
};

export const list: List = {
  "id": "5a6ebde81519395731f90e2f",
  "hash": "26873fa18b3a3c5bfd82f9d8e2dafa05",
  "avatar": "https://cdn.workast.io/list-avatar.png",
  "name": "Engineering",
  "numberOfParticipants": 2,
  "type": "group",
  "privacy": "private",
  "platformDetails": {
    "name": "slack",
    "channelId": "G8TRB56E8",
    "channelName": "engineering",
    "type": "group",
    "teamId": "T0HBUA0TC"
  },
  "isArchived": false,
  "createdBy": "b2956627fe26a2c1e4b6d5202413f779",
  "participants": [
    "4214932441cb21eebdb396bfe34a8340",
    "c51a9c1a2ddfbcefa7abf74036e0c616",
    "b2956627fe26a2c1e4b6d5202413f779"
  ],
  "platformNotifications": {
    "taskCreated": true,
    "taskCompleted": true
  },
  "apps": [
    {
      "id": "5af007dff36d2837eae6e56c",
      "name": "Slack",
      "description": "Ship v3",
      "icon": "https://cdn.workast.io/integrations/Slack/icon.png",
      "updatedAt": "2023-11-15T03:23:37.468Z",
      "clientId": "nUsktT5eDzpbJE15WLfMejf9oJ",
      "accessType": "user",
      "developedByWorkast": true,
      "integration": {
        "spaceActions": [
          {
            "actionId": "SHOW_SETTINGS",
            "label": "Slack"
          }
        ],
        "taskActions": []
      }
    },
    {
      "id": "5b23da45e7179a589282a60c",
      "name": "Email",
      "description": "Ship v3",
      "icon": "https://cdn.workast.io/integrations/Email/icon.png",
      "updatedAt": "2020-03-06T21:14:00.371Z",
      "clientId": "Jr5LKksQ9PZhr89R3l93aaaaab",
      "accessType": "user",
      "developedByWorkast": true,
      "integration": {
        "spaceActions": [
          {
            "actionId": "SHOW_SETTINGS",
            "label": "Email"
          }
        ],
        "taskActions": []
      }
    }
  ],
  "defaultSubList": "5a6ebde81519395731f90e30",
  "subLists": [
    {
      "id": "5a6ebde81519395731f90e30",
      "name": "To-do",
      "listPosition": 100000,
      "createdBy": "b2956627fe26a2c1e4b6d5202413f779"
    }
  ],
  "link": "https://app.workast.com/list/5a6ebde81519395731f90e2f",
  "isParticipant": true,
  "someParticipants": [
    {
      "id": "4214932441cb21eebdb396bfe34a8340",
      "name": "Grace Hopper",
      "userName": "grace",
      "email": "grace@example.com",
      "platformDetails": {
        "name": "slack",
        "imChannel": "D3EEXS3J6",
        "selfChannel": "D1HN843U3",
        "userId": "U0HBQESA1",
        "teamId": "T0HBUA0TC"
      },
      "confirmed": true,
      "avatar": "https://cdn.workast.io/avatar.png",
      "costCenter": "5c1b92b0a57d2b342c1a610e"
    },
    {
      "id": "b2956627fe26a2c1e4b6d5202413f779",
      "name": "Ada Lovelace",
      "userName": "ada",
      "email": "ada@example.com",
      "platformDetails": {
        "name": "slack",
        "imChannel": "D3F5RQA6B",
        "selfChannel": "D1LGYBCFQ",
        "userId": "U0JU26WRG",
        "teamId": "T0HBUA0TC"
      },
      "confirmed": true,
      "avatar": "https://cdn.workast.io/avatar.png",
      "costCenter": "5c1b92b0a57d2b342c1a610e"
    }
  ],
  "columns": [
    "assignedTo",
    "dueDate",
    "doneBy",
    "doneAt"
  ],
  "groupBy": "subList",
  "isBookmarked": false
};

export const listEnumerate: ListEnumerate = {
  "id": "5a6ebde81519395731f90e2f",
  "hash": "26873fa18b3a3c5bfd82f9d8e2dafa05",
  "name": "Engineering",
  "createdAt": "2018-01-29T06:23:36.194Z",
  "createdBy": {
    "id": "b2956627fe26a2c1e4b6d5202413f779",
    "name": "Ada Lovelace",
    "userName": "ada",
    "email": "ada@example.com",
    "platformDetails": {
      "name": "slack",
      "imChannel": "D3F5RQA6B",
      "selfChannel": "D1LGYBCFQ",
      "userId": "U0JU26WRG",
      "teamId": "T0HBUA0TC"
    },
    "confirmed": true,
    "avatar": "https://cdn.workast.io/avatar.png",
    "costCenter": "5c1b92b0a57d2b342c1a610e"
  },
  "avatar": "https://cdn.workast.io/list-avatar.png",
  "numberOfParticipants": 3,
  "type": "group",
  "privacy": "private",
  "isArchived": false,
  "platformDetails": {
    "name": "slack",
    "channelId": "G8TRB56E8",
    "channelName": "engineering",
    "type": "group",
    "teamId": "T0HBUA0TC"
  },
  "platformNotifications": {
    "taskCreated": true,
    "taskCompleted": true
  },
  "subLists": [
    {
      "id": "5a6ebde81519395731f90e30",
      "name": "To-do",
      "listPosition": 100000,
      "createdBy": "b2956627fe26a2c1e4b6d5202413f779"
    }
  ],
  "defaultSubList": "5a6ebde81519395731f90e30",
  "isParticipant": true,
  "link": "https://app.workast.com/list/5a6ebde81519395731f90e2f"
};

export const meeting: Meeting = {
  "id": "6a844c4c6bc4270979c79d34",
  "createdAt": "2026-08-18T12:13:00.327Z",
  "updatedAt": "2026-08-18T12:13:00.327Z",
  "summary": "Standup",
  "status": "active",
  "eventId": "2bi7qgtg2k615gsm4fom4oa2l8",
  "isRecurrent": false,
  "organizer": {
    "id": "4214932441cb21eebdb396bfe34a8340",
    "name": "Grace Hopper",
    "userName": "grace",
    "email": "grace@example.com",
    "platformDetails": {
      "name": "slack",
      "imChannel": "D3EEXS3J6",
      "selfChannel": "D1HN843U3",
      "userId": "U0HBQESA1",
      "teamId": "T0HBUA0TC"
    },
    "confirmed": true,
    "avatar": "https://cdn.workast.io/avatar.png",
    "costCenter": "5c1b92b0a57d2b342c1a610e"
  },
  "totalAttendees": 1,
  "someAttendees": [],
  "list": {
    "id": "5a6ebde81519395731f90e2f",
    "name": "Engineering",
    "type": "group",
    "status": "active",
    "privacy": "private",
    "link": "https://app.workast.com/list/5a6ebde81519395731f90e2f"
  },
  "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49/meeting/6a844c4c6bc4270979c79d34",
  "notetaker": {
    "enabled": false
  },
  "start": "2026-09-01T15:00:00.000Z",
  "end": "2026-09-01T15:30:00.000Z",
  "allDay": false
};

export const meetingDetail: MeetingDetail = {
  "id": "6a6840c6cc9ea3097a801627",
  "createdAt": "2026-07-28T05:40:22.966Z",
  "updatedAt": "2026-08-11T01:56:10.130Z",
  "summary": "Standup",
  "status": "active",
  "eventId": "gobiji6ddnsgaausdrhftf2cb2_20260728T223000Z",
  "isRecurrent": true,
  "organizer": {
    "id": "4214932441cb21eebdb396bfe34a8340",
    "name": "Grace Hopper",
    "userName": "grace",
    "email": "grace@example.com",
    "platformDetails": {
      "name": "slack",
      "imChannel": "D3EEXS3J6",
      "selfChannel": "D1HN843U3",
      "userId": "U0HBQESA1",
      "teamId": "T0HBUA0TC"
    },
    "confirmed": true,
    "avatar": "https://cdn.workast.io/avatar.png",
    "costCenter": "5c1b92b0a57d2b342c1a610e"
  },
  "totalAttendees": 2,
  "someAttendees": [
    {
      "id": "4214932441cb21eebdb396bfe34a8340",
      "name": "Grace Hopper",
      "userName": "grace",
      "email": "grace@example.com",
      "platformDetails": {
        "name": "slack",
        "imChannel": "D3EEXS3J6",
        "selfChannel": "D1HN843U3",
        "userId": "U0HBQESA1",
        "teamId": "T0HBUA0TC"
      },
      "confirmed": true,
      "avatar": "https://cdn.workast.io/avatar.png",
      "costCenter": "5c1b92b0a57d2b342c1a610e"
    }
  ],
  "list": {
    "id": "5fc58f3d15ff9110b64ca426",
    "type": "group",
    "status": "active",
    "privacy": "team",
    "link": "https://app.workast.com/list/5fc58f3d15ff9110b64ca426",
    "name": "Product"
  },
  "link": "https://app.workast.com/meeting/6a6840c6cc9ea3097a801627",
  "conferenceData": {
    "joinUrl": "https://example.com/file",
    "provider": "Google Meet"
  },
  "notetaker": {
    "enabled": false
  },
  "start": "2026-07-31T00:30:00.000Z",
  "end": "2026-07-31T02:00:00.000Z",
  "allDay": false,
  "totalTasks": 0,
  "completedTasks": 0
};

export const meetingRecordingResource: MeetingRecordingResource = {
  "transcript": {
    "object": "transcript",
    "type": "speaker_labelled",
    "language": "es",
    "transcript": [
      {
        "speaker": "Speaker A",
        "start": 37850,
        "end": 116040,
        "text": "Standup"
      }
    ]
  }
};

export const meetings: Meetings = {
  "meetings": [
    {
      "id": "6a6840c6cc9ea3097a801627",
      "summary": "Standup",
      "eventId": "gobiji6ddnsgaausdrhftf2cb2_20260728T223000Z",
      "isRecurrent": true,
      "organizer": {
        "id": "4214932441cb21eebdb396bfe34a8340",
        "name": "Grace Hopper",
        "userName": "grace",
        "email": "grace@example.com",
        "platformDetails": {
          "name": "slack",
          "imChannel": "D3EEXS3J6",
          "selfChannel": "D1HN843U3",
          "userId": "U0HBQESA1",
          "teamId": "T0HBUA0TC"
        },
        "confirmed": true,
        "avatar": "https://cdn.workast.io/avatar.png",
        "costCenter": "5c1b92b0a57d2b342c1a610e"
      },
      "totalAttendees": 2,
      "someAttendees": [
        {
          "id": "4214932441cb21eebdb396bfe34a8340",
          "name": "Grace Hopper",
          "userName": "grace",
          "email": "grace@example.com",
          "platformDetails": {
            "name": "slack",
            "imChannel": "D3EEXS3J6",
            "selfChannel": "D1HN843U3",
            "userId": "U0HBQESA1",
            "teamId": "T0HBUA0TC"
          },
          "confirmed": true,
          "avatar": "https://cdn.workast.io/avatar.png",
          "costCenter": "5c1b92b0a57d2b342c1a610e"
        },
        {
          "id": "67c6206fc7cb0feb115113cdf71aa72d",
          "name": "Katherine Johnson",
          "userName": "katherine",
          "email": "katherine@example.com",
          "platformDetails": {
            "name": "slack",
            "imChannel": "D06JN8RT8KB",
            "selfChannel": "D06HV290V6K",
            "userId": "U06J9JSF6R0",
            "teamId": "T0HBUA0TC"
          },
          "confirmed": false,
          "avatar": "https://cdn.workast.io/avatar.png",
          "costCenter": "5c1b92b0a57d2b342c1a610e"
        }
      ],
      "link": "https://app.workast.com/meeting/6a6840c6cc9ea3097a801627",
      "start": "2026-07-31T00:30:00.000Z",
      "end": "2026-07-31T02:00:00.000Z",
      "allDay": false,
      "totalTasks": 0,
      "completedTasks": 0
    }
  ],
  "nextPageToken": "eyJzdGFydCI6IjIwMjYtMDctMzFUMDA6MzA6MDAuMDAwWiIsImlkIjoiNmE2ODQwYzZjYzllYTMwOTdhODAxNjI3In0"
};

export const note: Note = {
  "id": "6994a3e051b10d097caddd0f",
  "title": "Ship v3",
  "createdAt": "2026-02-17T17:22:40.359Z",
  "updatedAt": "2026-02-23T22:00:53.158Z",
  "version": 58,
  "list": {
    "id": "6938534c1679f90979e5ccf4",
    "avatar": "https://cdn.workast.io/list-avatar.png",
    "name": "Engineering",
    "numberOfParticipants": 2,
    "type": "group",
    "slug": "engineering",
    "privacy": "team",
    "platformDetails": {
      "type": "group"
    },
    "isArchived": false,
    "createdBy": "67c6206fc7cb0feb115113cdf71aa72d",
    "participants": [
      "67c6206fc7cb0feb115113cdf71aa72d",
      "4214932441cb21eebdb396bfe34a8340"
    ],
    "platformNotifications": {
      "taskCreated": true,
      "taskCompleted": true
    },
    "apps": [
      {
        "id": "5b23da45e7179a589282a60c",
        "name": "Email",
        "description": "Ship v3",
        "icon": "https://cdn.workast.io/integrations/Email/icon.png",
        "updatedAt": "2020-03-06T21:14:00.371Z",
        "clientId": "Jr5LKksQ9PZhr89R3l93aaaaab",
        "accessType": "user",
        "developedByWorkast": true,
        "integration": {
          "spaceActions": [
            {
              "actionId": "SHOW_SETTINGS",
              "label": "Email"
            }
          ],
          "taskActions": []
        }
      },
      {
        "name": "Example App",
        "description": "Ship v3",
        "icon": "https://cdn.workast.io/avatar.png",
        "createdAt": "2019-10-06T22:30:33.687Z",
        "updatedAt": "2020-03-06T21:14:00.371Z",
        "clientId": "S4GuidJp6frYrxLTuQBM5JoTug",
        "accessType": "user",
        "developedByWorkast": true,
        "id": "5d83a3de767119000151da7a"
      }
    ],
    "defaultSubList": "6938534c1679f90979e5ccf3",
    "subLists": [
      {
        "id": "6938534c1679f90979e5ccf3",
        "name": "To-do",
        "listPosition": 100000,
        "createdBy": "67c6206fc7cb0feb115113cdf71aa72d"
      },
      {
        "id": "693853701679f90979e5d186",
        "name": "In Progress",
        "listPosition": 200000,
        "createdBy": "67c6206fc7cb0feb115113cdf71aa72d"
      }
    ],
    "link": "https://app.workast.com/list/6938534c1679f90979e5ccf4",
    "isParticipant": true,
    "someParticipants": [
      {
        "id": "67c6206fc7cb0feb115113cdf71aa72d",
        "name": "Katherine Johnson",
        "userName": "katherine",
        "email": "katherine@example.com",
        "platformDetails": {
          "name": "slack",
          "imChannel": "D06JN8RT8KB",
          "selfChannel": "D06HV290V6K",
          "userId": "U06J9JSF6R0",
          "teamId": "T0HBUA0TC"
        },
        "confirmed": false,
        "avatar": "https://cdn.workast.io/avatar.png",
        "costCenter": "5c1b92b0a57d2b342c1a610e"
      }
    ],
    "columns": [
      "assignedTo",
      "dueDate",
      "doneBy",
      "doneAt"
    ],
    "groupBy": "subList"
  },
  "createdBy": {
    "id": "67c6206fc7cb0feb115113cdf71aa72d",
    "name": "Katherine Johnson",
    "userName": "katherine",
    "email": "katherine@example.com",
    "platformDetails": {
      "name": "slack",
      "imChannel": "D06JN8RT8KB",
      "selfChannel": "D06HV290V6K",
      "userId": "U06J9JSF6R0",
      "teamId": "T0HBUA0TC"
    },
    "confirmed": false,
    "avatar": "https://cdn.workast.io/avatar.png",
    "costCenter": "5c1b92b0a57d2b342c1a610e"
  }
};

export const noteDetail: NoteDetail = {
  "id": "6994a3e051b10d097caddd0f",
  "title": "Ship v3",
  "createdAt": "2026-02-17T17:22:40.359Z",
  "updatedAt": "2026-02-23T22:00:53.158Z",
  "version": 58,
  "list": {
    "id": "6938534c1679f90979e5ccf4",
    "avatar": "https://cdn.workast.io/list-avatar.png",
    "name": "Engineering",
    "numberOfParticipants": 2,
    "type": "group",
    "slug": "engineering",
    "privacy": "team",
    "platformDetails": {
      "type": "group"
    },
    "isArchived": false,
    "createdBy": "67c6206fc7cb0feb115113cdf71aa72d",
    "participants": [
      "67c6206fc7cb0feb115113cdf71aa72d",
      "4214932441cb21eebdb396bfe34a8340"
    ],
    "platformNotifications": {
      "taskCreated": true,
      "taskCompleted": true
    },
    "apps": [
      {
        "id": "5b23da45e7179a589282a60c",
        "name": "Email",
        "description": "Ship v3",
        "icon": "https://cdn.workast.io/integrations/Email/icon.png",
        "updatedAt": "2020-03-06T21:14:00.371Z",
        "clientId": "Jr5LKksQ9PZhr89R3l93aaaaab",
        "accessType": "user",
        "developedByWorkast": true,
        "integration": {
          "spaceActions": [
            {
              "actionId": "SHOW_SETTINGS",
              "label": "Email"
            }
          ],
          "taskActions": []
        }
      },
      {
        "name": "Example App",
        "description": "Ship v3",
        "icon": "https://cdn.workast.io/avatar.png",
        "createdAt": "2019-10-06T22:30:33.687Z",
        "updatedAt": "2020-03-06T21:14:00.371Z",
        "clientId": "S4GuidJp6frYrxLTuQBM5JoTug",
        "accessType": "user",
        "developedByWorkast": true,
        "id": "5d83a3de767119000151da7a"
      }
    ],
    "defaultSubList": "6938534c1679f90979e5ccf3",
    "subLists": [
      {
        "id": "6938534c1679f90979e5ccf3",
        "name": "To-do",
        "listPosition": 100000,
        "createdBy": "67c6206fc7cb0feb115113cdf71aa72d"
      },
      {
        "id": "693853701679f90979e5d186",
        "name": "In Progress",
        "listPosition": 200000,
        "createdBy": "67c6206fc7cb0feb115113cdf71aa72d"
      }
    ],
    "link": "https://app.workast.com/list/6938534c1679f90979e5ccf4",
    "isParticipant": true,
    "someParticipants": [
      {
        "id": "67c6206fc7cb0feb115113cdf71aa72d",
        "name": "Katherine Johnson",
        "userName": "katherine",
        "email": "katherine@example.com",
        "platformDetails": {
          "name": "slack",
          "imChannel": "D06JN8RT8KB",
          "selfChannel": "D06HV290V6K",
          "userId": "U06J9JSF6R0",
          "teamId": "T0HBUA0TC"
        },
        "confirmed": false,
        "avatar": "https://cdn.workast.io/avatar.png",
        "costCenter": "5c1b92b0a57d2b342c1a610e"
      }
    ],
    "columns": [
      "assignedTo",
      "dueDate",
      "doneBy",
      "doneAt"
    ],
    "groupBy": "subList"
  },
  "createdBy": {
    "id": "67c6206fc7cb0feb115113cdf71aa72d",
    "name": "Katherine Johnson",
    "userName": "katherine",
    "email": "katherine@example.com",
    "platformDetails": {
      "name": "slack",
      "imChannel": "D06JN8RT8KB",
      "selfChannel": "D06HV290V6K",
      "userId": "U06J9JSF6R0",
      "teamId": "T0HBUA0TC"
    },
    "confirmed": false,
    "avatar": "https://cdn.workast.io/avatar.png",
    "costCenter": "5c1b92b0a57d2b342c1a610e"
  },
  "body": "<p>Ship v3</p>"
};

export const notes: Notes = {
  "notes": [
    {
      "id": "6994a3e051b10d097caddd0f",
      "title": "Ship v3",
      "createdAt": "2026-02-17T17:22:40.359Z",
      "updatedAt": "2026-02-23T22:00:53.158Z",
      "version": 58,
      "list": {
        "id": "6938534c1679f90979e5ccf4",
        "avatar": "https://cdn.workast.io/list-avatar.png",
        "name": "Engineering",
        "numberOfParticipants": 2,
        "type": "group",
        "slug": "engineering",
        "privacy": "team",
        "platformDetails": {
          "type": "group"
        },
        "isArchived": false,
        "createdBy": "67c6206fc7cb0feb115113cdf71aa72d",
        "participants": [
          "67c6206fc7cb0feb115113cdf71aa72d",
          "4214932441cb21eebdb396bfe34a8340"
        ],
        "platformNotifications": {
          "taskCreated": true,
          "taskCompleted": true
        },
        "apps": [
          {
            "id": "5b23da45e7179a589282a60c",
            "name": "Email",
            "description": "Ship v3",
            "icon": "https://cdn.workast.io/integrations/Email/icon.png",
            "updatedAt": "2020-03-06T21:14:00.371Z",
            "clientId": "Jr5LKksQ9PZhr89R3l93aaaaab",
            "accessType": "user",
            "developedByWorkast": true,
            "integration": {
              "spaceActions": [
                {
                  "actionId": "SHOW_SETTINGS",
                  "label": "Email"
                }
              ],
              "taskActions": []
            }
          },
          {
            "name": "Example App",
            "description": "Ship v3",
            "icon": "https://cdn.workast.io/avatar.png",
            "createdAt": "2019-10-06T22:30:33.687Z",
            "updatedAt": "2020-03-06T21:14:00.371Z",
            "clientId": "S4GuidJp6frYrxLTuQBM5JoTug",
            "accessType": "user",
            "developedByWorkast": true,
            "id": "5d83a3de767119000151da7a"
          }
        ],
        "defaultSubList": "6938534c1679f90979e5ccf3",
        "subLists": [
          {
            "id": "6938534c1679f90979e5ccf3",
            "name": "To-do",
            "listPosition": 100000,
            "createdBy": "67c6206fc7cb0feb115113cdf71aa72d"
          },
          {
            "id": "693853701679f90979e5d186",
            "name": "In Progress",
            "listPosition": 200000,
            "createdBy": "67c6206fc7cb0feb115113cdf71aa72d"
          }
        ],
        "link": "https://app.workast.com/list/6938534c1679f90979e5ccf4",
        "isParticipant": true,
        "someParticipants": [
          {
            "id": "67c6206fc7cb0feb115113cdf71aa72d",
            "name": "Katherine Johnson",
            "userName": "katherine",
            "email": "katherine@example.com",
            "platformDetails": {
              "name": "slack",
              "imChannel": "D06JN8RT8KB",
              "selfChannel": "D06HV290V6K",
              "userId": "U06J9JSF6R0",
              "teamId": "T0HBUA0TC"
            },
            "confirmed": false,
            "avatar": "https://cdn.workast.io/avatar.png",
            "costCenter": "5c1b92b0a57d2b342c1a610e"
          }
        ],
        "columns": [
          "assignedTo",
          "dueDate",
          "doneBy",
          "doneAt"
        ],
        "groupBy": "subList"
      },
      "createdBy": {
        "id": "67c6206fc7cb0feb115113cdf71aa72d",
        "name": "Katherine Johnson",
        "userName": "katherine",
        "email": "katherine@example.com",
        "platformDetails": {
          "name": "slack",
          "imChannel": "D06JN8RT8KB",
          "selfChannel": "D06HV290V6K",
          "userId": "U06J9JSF6R0",
          "teamId": "T0HBUA0TC"
        },
        "confirmed": false,
        "avatar": "https://cdn.workast.io/avatar.png",
        "costCenter": "5c1b92b0a57d2b342c1a610e"
      }
    }
  ],
  "total": 168
};

export const notifications: Notifications = {
  "notifications": [
    {
      "id": "6a7ea6b48e9808acbda8914f",
      "type": "meeting_media_ready",
      "read": false,
      "activityId": "6a7ea6b48e9808acbda89147",
      "sentAt": "2026-08-14T05:25:08.472Z",
      "createdAt": "2026-08-14T05:25:08.474Z",
      "content": {
        "actor": {
          "type": "App",
          "id": {
            "id": "5ed17524aa2ab23bf71d324d",
            "name": "Meetings",
            "icon": "https://cdn.workast.io/avatar.png"
          }
        },
        "message": "Standup"
      },
      "activityType": "meeting_media_ready"
    }
  ],
  "total": 2244
};

export const reactionReadOnly: ReactionReadOnly = {
  "id": "6a844d5e6bc4270979c7a8ee",
  "emoji": ":+1:",
  "total": 1,
  "users": [
    {
      "name": "Grace Hopper"
    }
  ]
};

export const search: Search = {
  "id": "5f0e23098d49422410c20540",
  "custom": true,
  "name": "Ship v3",
  "payload": {
    "sort": [
      {
        "direction": 1,
        "field": "listName"
      }
    ],
    "includeSubTasks": true,
    "predicates": [
      {
        "value": "pending",
        "comparison": "eq",
        "attribute": "status",
        "type": "status"
      }
    ],
    "columns": [
      "list"
    ]
  },
  "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49/search/5f0e23098d49422410c20540",
  "isPrimary": false,
  "users": [],
  "createdBy": {
    "user": {
      "id": "4214932441cb21eebdb396bfe34a8340",
      "name": "Grace Hopper",
      "userName": "grace",
      "email": "grace@example.com",
      "platformDetails": {
        "name": "slack",
        "imChannel": "D3EEXS3J6",
        "selfChannel": "D1HN843U3",
        "userId": "U0HBQESA1",
        "teamId": "T0HBUA0TC"
      },
      "confirmed": true,
      "avatar": "https://cdn.workast.io/avatar.png",
      "costCenter": "5c1b92b0a57d2b342c1a610e"
    }
  },
  "createdAt": "2020-07-14T21:26:33.254Z",
  "updatedAt": "2023-05-31T23:15:19.277Z",
  "values": {
    "list": {
      "5a99a7a58373fa652992e665": {
        "id": "5a99a7a58373fa652992e665",
        "type": "group",
        "status": "active",
        "privacy": "team",
        "link": "https://app.workast.com/list/5a99a7a58373fa652992e665",
        "name": "Engineering"
      },
      "5dc40cff038a590f79c403c0": {
        "id": "5dc40cff038a590f79c403c0",
        "type": "group",
        "status": "active",
        "privacy": "team",
        "link": "https://app.workast.com/list/5dc40cff038a590f79c403c0",
        "name": "Product"
      },
      "5fc58f3d15ff9110b64ca426": {
        "id": "5fc58f3d15ff9110b64ca426",
        "type": "group",
        "status": "active",
        "privacy": "team",
        "link": "https://app.workast.com/list/5fc58f3d15ff9110b64ca426",
        "name": "Engineering"
      }
    }
  }
};

export const searchDetail: SearchDetail = {
  "id": "5ddfeab45ff6d925d23c929e",
  "custom": true,
  "name": "Ship v3",
  "payload": {
    "includeSubTasks": true,
    "predicates": [
      {
        "value": "pending",
        "comparison": "eq",
        "attribute": "status",
        "type": "status"
      },
      {
        "predicates": [
          {
            "value": "5a176b5aa67ba147e5057516",
            "comparison": "eq",
            "attribute": "listId",
            "type": "list"
          },
          {
            "value": "5d7be323c662860f7c97ba12",
            "comparison": "eq",
            "attribute": "listId",
            "type": "list"
          },
          {
            "value": "5de581bdf2cec034545231fb",
            "comparison": "eq",
            "attribute": "listId",
            "type": "list"
          },
          {
            "value": "5de5818df2cec034545231a2",
            "comparison": "eq",
            "attribute": "listId",
            "type": "list"
          },
          {
            "value": "5dc40cff038a590f79c403c0",
            "comparison": "eq",
            "attribute": "listId",
            "type": "list"
          },
          {
            "type": "list",
            "attribute": "listId",
            "comparison": "eq",
            "value": "5e3d61b624e278106e8f6cf1"
          },
          {
            "type": "list",
            "attribute": "listId",
            "comparison": "eq",
            "value": "5f230805bf972326deafab16"
          },
          {
            "type": "list",
            "attribute": "listId",
            "comparison": "eq",
            "value": "5fc58f3d15ff9110b64ca426"
          }
        ],
        "type": "or"
      },
      {
        "value": "4214932441cb21eebdb396bfe34a8340",
        "comparison": "eq",
        "attribute": "assignedTo",
        "type": "user"
      }
    ],
    "sort": [
      {
        "field": "listName",
        "direction": 1
      }
    ],
    "columns": [
      "list",
      "subList",
      "assignedTo",
      "dueDate"
    ]
  },
  "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49/search/5ddfeab45ff6d925d23c929e",
  "isPrimary": false,
  "users": [],
  "createdBy": {
    "user": {
      "id": "4214932441cb21eebdb396bfe34a8340",
      "name": "Grace Hopper",
      "userName": "grace",
      "email": "grace@example.com",
      "platformDetails": {
        "name": "slack",
        "imChannel": "D3EEXS3J6",
        "selfChannel": "D1HN843U3",
        "userId": "U0HBQESA1",
        "teamId": "T0HBUA0TC"
      },
      "confirmed": true,
      "avatar": "https://cdn.workast.io/avatar.png",
      "costCenter": "5c1b92b0a57d2b342c1a610e"
    }
  },
  "createdAt": "2019-11-28T15:41:40.245Z",
  "updatedAt": "2021-01-14T18:44:34.151Z",
  "values": {
    "list": {
      "5a176b5aa67ba147e5057516": {
        "id": "5a176b5aa67ba147e5057516",
        "type": "group",
        "status": "archived",
        "privacy": "team",
        "link": "https://app.workast.com/list/5a176b5aa67ba147e5057516",
        "name": "Engineering"
      },
      "5d7be323c662860f7c97ba12": {
        "id": "5d7be323c662860f7c97ba12",
        "type": "group",
        "status": "archived",
        "privacy": "team",
        "link": "https://app.workast.com/list/5d7be323c662860f7c97ba12",
        "name": "Product"
      },
      "5dc40cff038a590f79c403c0": {
        "id": "5dc40cff038a590f79c403c0",
        "type": "group",
        "status": "active",
        "privacy": "team",
        "link": "https://app.workast.com/list/5dc40cff038a590f79c403c0",
        "name": "Product"
      },
      "5de5818df2cec034545231a2": {
        "id": "5de5818df2cec034545231a2",
        "type": "group",
        "status": "archived",
        "privacy": "team",
        "link": "https://app.workast.com/list/5de5818df2cec034545231a2",
        "name": "Product"
      },
      "5de581bdf2cec034545231fb": {
        "id": "5de581bdf2cec034545231fb",
        "type": "group",
        "status": "archived",
        "privacy": "team",
        "link": "https://app.workast.com/list/5de581bdf2cec034545231fb",
        "name": "Product"
      },
      "5e3d61b624e278106e8f6cf1": {
        "id": "5e3d61b624e278106e8f6cf1",
        "type": "group",
        "status": "archived",
        "privacy": "team",
        "link": "https://app.workast.com/list/5e3d61b624e278106e8f6cf1",
        "name": "Product"
      },
      "5f230805bf972326deafab16": {
        "id": "5f230805bf972326deafab16",
        "type": "group",
        "status": "active",
        "privacy": "team",
        "link": "https://app.workast.com/list/5f230805bf972326deafab16",
        "name": "Product"
      },
      "5fc58f3d15ff9110b64ca426": {
        "id": "5fc58f3d15ff9110b64ca426",
        "type": "group",
        "status": "active",
        "privacy": "team",
        "link": "https://app.workast.com/list/5fc58f3d15ff9110b64ca426",
        "name": "Product"
      }
    },
    "user": {
      "4214932441cb21eebdb396bfe34a8340": {
        "id": "4214932441cb21eebdb396bfe34a8340",
        "name": "Grace Hopper",
        "userName": "grace",
        "email": "grace@example.com",
        "platformDetails": {
          "name": "slack",
          "imChannel": "D3EEXS3J6",
          "selfChannel": "D1HN843U3",
          "userId": "U0HBQESA1",
          "teamId": "T0HBUA0TC"
        },
        "confirmed": true,
        "avatar": "https://cdn.workast.io/avatar.png",
        "costCenter": "5c1b92b0a57d2b342c1a610e"
      }
    }
  },
  "results": {
    "tasks": [
      {
        "status": "pending",
        "text": "Ship v3",
        "shortId": "TGNT8",
        "createdAt": "2026-07-30T11:06:01.976Z",
        "updatedAt": "2026-08-03T04:47:29.070Z",
        "listPosition": -400001,
        "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49/task/11c933fd54aab8cfe9957ab46ccb401f",
        "calendars": [
          "4214932441cb21eebdb396bfe34a8340"
        ],
        "id": "11c933fd54aab8cfe9957ab46ccb401f",
        "list": {
          "id": "5dc40cff038a590f79c403c0",
          "name": "Development Product",
          "type": "group",
          "privacy": "team",
          "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49/space/5dc40cff038a590f79c403c0",
          "subLists": [
            {
              "id": "5dc40d3f7e802c0f93f20232",
              "name": "Live testing",
              "listPosition": 100000,
              "createdBy": "4214932441cb21eebdb396bfe34a8340"
            }
          ]
        },
        "listId": "5dc40cff038a590f79c403c0",
        "subListId": "5dc40d3f7e802c0f93f20232",
        "subList": {
          "id": "5dc40d3f7e802c0f93f20232",
          "name": "Live testing"
        },
        "assignedTo": [
          {
            "id": "4214932441cb21eebdb396bfe34a8340",
            "name": "Grace Hopper",
            "userName": "grace",
            "email": "grace@example.com",
            "platformDetails": {
              "name": "slack",
              "imChannel": "D3EEXS3J6",
              "selfChannel": "D1HN843U3",
              "userId": "U0HBQESA1",
              "teamId": "T0HBUA0TC"
            },
            "confirmed": true,
            "avatar": "https://cdn.workast.io/avatar.png",
            "costCenter": "5c1b92b0a57d2b342c1a610e"
          }
        ],
        "subscribers": [
          {
            "id": "4214932441cb21eebdb396bfe34a8340",
            "name": "Grace Hopper",
            "userName": "grace",
            "email": "grace@example.com",
            "platformDetails": {
              "name": "slack",
              "imChannel": "D3EEXS3J6",
              "selfChannel": "D1HN843U3",
              "userId": "U0HBQESA1",
              "teamId": "T0HBUA0TC"
            },
            "confirmed": true,
            "avatar": "https://cdn.workast.io/avatar.png",
            "costCenter": "5c1b92b0a57d2b342c1a610e"
          }
        ],
        "allDay": false,
        "createdBy": {
          "id": "4214932441cb21eebdb396bfe34a8340",
          "name": "Grace Hopper",
          "userName": "grace",
          "email": "grace@example.com",
          "platformDetails": {
            "name": "slack",
            "imChannel": "D3EEXS3J6",
            "selfChannel": "D1HN843U3",
            "userId": "U0HBQESA1",
            "teamId": "T0HBUA0TC"
          },
          "confirmed": true,
          "avatar": "https://cdn.workast.io/avatar.png",
          "costCenter": "5c1b92b0a57d2b342c1a610e"
        },
        "hasDescription": true,
        "numberOfComments": 0,
        "numberOfAttachments": 0,
        "totalSubTasks": 2,
        "completedSubTasks": 2,
        "isSubscribed": true,
        "taskStatus": {
          "id": "5c7184fa40721e2ed4175a6e",
          "label": "Open",
          "color": "#808080",
          "createdAt": "2019-02-23T17:38:02.928Z",
          "updatedAt": "2019-02-23T17:38:02.928Z"
        },
        "milestones": [],
        "inHome": false,
        "fields": []
      }
    ],
    "total": 12,
    "hiddenTasks": 0
  }
};

export const searchResults: SearchResults = {
  "tasks": [
    {
      "status": "pending",
      "text": "Ship v3",
      "shortId": "T4GNY",
      "createdAt": "2022-01-10T12:12:46.308Z",
      "updatedAt": "2025-07-10T08:25:54.460Z",
      "listPosition": 99999,
      "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49/task/3634dc043f0d415ec2d307284a3cfe69",
      "calendars": [
        "b2956627fe26a2c1e4b6d5202413f779"
      ],
      "id": "3634dc043f0d415ec2d307284a3cfe69",
      "list": {
        "id": "603449f6f107b67c63e8cee9",
        "name": "Product",
        "type": "group",
        "privacy": "private",
        "link": "https://app.workast.com/list/603449f6f107b67c63e8cee9",
        "subLists": [
          {
            "id": "603449f6f107b67c63e8cee8",
            "name": "To-do",
            "listPosition": 100000,
            "createdBy": "4214932441cb21eebdb396bfe34a8340"
          },
          {
            "id": "610ffd8c7374d6331a4178d8",
            "name": "In Progress",
            "listPosition": 700000,
            "createdBy": "4214932441cb21eebdb396bfe34a8340"
          }
        ]
      },
      "listId": "603449f6f107b67c63e8cee9",
      "subListId": "610ffd8c7374d6331a4178d8",
      "subList": {
        "id": "610ffd8c7374d6331a4178d8",
        "name": "To-do"
      },
      "assignedTo": [
        {
          "id": "b2956627fe26a2c1e4b6d5202413f779",
          "name": "Ada Lovelace",
          "userName": "ada",
          "email": "ada@example.com",
          "platformDetails": {
            "name": "slack",
            "imChannel": "D3F5RQA6B",
            "selfChannel": "D1LGYBCFQ",
            "userId": "U0JU26WRG",
            "teamId": "T0HBUA0TC"
          },
          "confirmed": true,
          "avatar": "https://cdn.workast.io/avatar.png",
          "costCenter": "5c1b92b0a57d2b342c1a610e"
        }
      ],
      "subscribers": [
        {
          "id": "b2956627fe26a2c1e4b6d5202413f779",
          "name": "Ada Lovelace",
          "userName": "ada",
          "email": "ada@example.com",
          "platformDetails": {
            "name": "slack",
            "imChannel": "D3F5RQA6B",
            "selfChannel": "D1LGYBCFQ",
            "userId": "U0JU26WRG",
            "teamId": "T0HBUA0TC"
          },
          "confirmed": true,
          "avatar": "https://cdn.workast.io/avatar.png",
          "costCenter": "5c1b92b0a57d2b342c1a610e"
        }
      ],
      "allDay": false,
      "createdBy": {
        "id": "b2956627fe26a2c1e4b6d5202413f779",
        "name": "Ada Lovelace",
        "userName": "ada",
        "email": "ada@example.com",
        "platformDetails": {
          "name": "slack",
          "imChannel": "D3F5RQA6B",
          "selfChannel": "D1LGYBCFQ",
          "userId": "U0JU26WRG",
          "teamId": "T0HBUA0TC"
        },
        "confirmed": true,
        "avatar": "https://cdn.workast.io/avatar.png",
        "costCenter": "5c1b92b0a57d2b342c1a610e"
      },
      "hasDescription": true,
      "numberOfComments": 1,
      "numberOfAttachments": 0,
      "totalSubTasks": 1,
      "completedSubTasks": 0,
      "isSubscribed": true,
      "lastComment": {
        "id": "686f7912fc2fef09733c6f58",
        "type": "comment",
        "value": "Standup",
        "status": "active",
        "createdAt": "2025-07-10T08:25:54.274Z",
        "updatedAt": "2025-07-10T08:25:54.274Z",
        "mentions": [
          {
            "id": "b2956627fe26a2c1e4b6d5202413f779",
            "name": "Ada Lovelace",
            "userName": "ada",
            "email": "ada@example.com",
            "platformDetails": {
              "name": "slack",
              "imChannel": "D3F5RQA6B",
              "selfChannel": "D1LGYBCFQ",
              "userId": "U0JU26WRG",
              "teamId": "T0HBUA0TC"
            },
            "confirmed": true,
            "avatar": "https://cdn.workast.io/avatar.png",
            "costCenter": "5c1b92b0a57d2b342c1a610e"
          }
        ],
        "reactions": [],
        "actor": {
          "type": "User",
          "data": {
            "id": "4214932441cb21eebdb396bfe34a8340",
            "name": "Grace Hopper",
            "userName": "grace",
            "email": "grace@example.com",
            "platformDetails": {
              "name": "slack",
              "imChannel": "D3EEXS3J6",
              "selfChannel": "D1HN843U3",
              "userId": "U0HBQESA1",
              "teamId": "T0HBUA0TC"
            },
            "confirmed": true,
            "avatar": "https://cdn.workast.io/avatar.png",
            "costCenter": "5c1b92b0a57d2b342c1a610e"
          }
        }
      },
      "taskStatus": {
        "id": "5c7184fa40721e2ed4175a6e",
        "label": "Open",
        "color": "#808080",
        "createdAt": "2019-02-23T17:38:02.928Z",
        "updatedAt": "2019-02-23T17:38:02.928Z"
      },
      "milestones": [],
      "inHome": false,
      "fields": []
    }
  ],
  "total": 441,
  "hiddenTasks": 0
};

export const searches: Searches = {
  "searches": [
    {
      "id": "5ddfeab45ff6d925d23c929e",
      "name": "Ship v3",
      "custom": true,
      "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49/search/5ddfeab45ff6d925d23c929e",
      "usersCount": 0,
      "createdBy": {
        "user": "4214932441cb21eebdb396bfe34a8340"
      },
      "createdAt": "2019-11-28T15:41:40.245Z",
      "updatedAt": "2021-01-14T18:44:34.151Z"
    }
  ],
  "total": 3
};

export const subList: SubList = {
  "id": "5a6ebde81519395731f90e30",
  "name": "To-do",
  "listPosition": 100000,
  "createdBy": "b2956627fe26a2c1e4b6d5202413f779"
};

export const tag: Tag = {
  "id": "5a6227d69f0cec2676083529",
  "name": "Feature",
  "color": "#61bd4f"
};

export const task: Task = {
  "id": "3634dc043f0d415ec2d307284a3cfe69",
  "createdAt": "2022-01-10T12:12:46.308Z",
  "createdBy": {
    "id": "b2956627fe26a2c1e4b6d5202413f779",
    "createdAt": "2016-12-28T22:19:45.715Z",
    "name": "Ada Lovelace",
    "userName": "ada",
    "platformDetails": {
      "name": "slack",
      "imChannel": "D3F5RQA6B",
      "selfChannel": "D1LGYBCFQ",
      "userId": "U0JU26WRG",
      "teamId": "T0HBUA0TC"
    },
    "timezone": "Australia/Canberra",
    "email": "ada@example.com",
    "lastActive": "2025-07-10T01:22:15.814Z",
    "role": "admin",
    "status": "active",
    "confirmed": true,
    "profile": {},
    "avatar": "https://cdn.workast.io/avatar.png",
    "costCenter": "5c1b92b0a57d2b342c1a610e"
  },
  "shortId": "T4GNY",
  "text": "Ship v3",
  "assignedTo": [
    {
      "id": "b2956627fe26a2c1e4b6d5202413f779",
      "createdAt": "2016-12-28T22:19:45.715Z",
      "name": "Ada Lovelace",
      "userName": "ada",
      "platformDetails": {
        "name": "slack",
        "imChannel": "D3F5RQA6B",
        "selfChannel": "D1LGYBCFQ",
        "userId": "U0JU26WRG",
        "teamId": "T0HBUA0TC"
      },
      "timezone": "Australia/Canberra",
      "email": "ada@example.com",
      "lastActive": "2025-07-10T01:22:15.814Z",
      "role": "admin",
      "status": "active",
      "confirmed": true,
      "profile": {},
      "avatar": "https://cdn.workast.io/avatar.png",
      "costCenter": "5c1b92b0a57d2b342c1a610e"
    }
  ],
  "subscribers": [
    {
      "id": "b2956627fe26a2c1e4b6d5202413f779",
      "createdAt": "2016-12-28T22:19:45.715Z",
      "name": "Ada Lovelace",
      "userName": "ada",
      "platformDetails": {
        "name": "slack",
        "imChannel": "D3F5RQA6B",
        "selfChannel": "D1LGYBCFQ",
        "userId": "U0JU26WRG",
        "teamId": "T0HBUA0TC"
      },
      "timezone": "Australia/Canberra",
      "email": "ada@example.com",
      "lastActive": "2025-07-10T01:22:15.814Z",
      "role": "admin",
      "status": "active",
      "confirmed": true,
      "profile": {},
      "avatar": "https://cdn.workast.io/avatar.png",
      "costCenter": "5c1b92b0a57d2b342c1a610e"
    },
    {
      "id": "4214932441cb21eebdb396bfe34a8340",
      "createdAt": "2017-04-14T02:14:44.247Z",
      "name": "Grace Hopper",
      "userName": "grace",
      "platformDetails": {
        "name": "slack",
        "imChannel": "D3EEXS3J6",
        "selfChannel": "D1HN843U3",
        "userId": "U0HBQESA1",
        "teamId": "T0HBUA0TC"
      },
      "timezone": "Australia/Canberra",
      "email": "grace@example.com",
      "lastActive": "2026-08-18T11:29:00.207Z",
      "role": "admin",
      "status": "active",
      "confirmed": true,
      "profile": {},
      "avatar": "https://cdn.workast.io/avatar.png",
      "costCenter": "5c1b92b0a57d2b342c1a610e"
    }
  ],
  "status": "pending",
  "allDay": false,
  "priority": 0,
  "description": "Ship v3",
  "listId": "603449f6f107b67c63e8cee9",
  "list": {
    "id": "603449f6f107b67c63e8cee9",
    "hash": "fabc9069cda279d762400d53e2854266",
    "name": "Product",
    "avatar": "https://cdn.workast.io/list-avatar.png",
    "numberOfParticipants": 2,
    "type": "group",
    "privacy": "private",
    "isArchived": false,
    "platformDetails": {
      "name": "slack",
      "channelId": "G01NLRJ053L",
      "channelName": "engineering",
      "type": "group",
      "teamId": "T0HBUA0TC"
    },
    "platformNotifications": {
      "taskCreated": true,
      "taskCompleted": true
    },
    "subLists": [
      {
        "id": "603449f6f107b67c63e8cee8",
        "name": "To-do",
        "listPosition": 100000,
        "createdBy": "4214932441cb21eebdb396bfe34a8340"
      },
      {
        "id": "610ffd8c7374d6331a4178d8",
        "name": "In Progress",
        "listPosition": 700000,
        "createdBy": "4214932441cb21eebdb396bfe34a8340"
      }
    ],
    "defaultSubList": "603449f6f107b67c63e8cee8",
    "isParticipant": true,
    "link": "https://app.workast.com/list/603449f6f107b67c63e8cee9"
  },
  "listPosition": 99999,
  "subList": {
    "id": "610ffd8c7374d6331a4178d8",
    "name": "To-do",
    "listPosition": 700000,
    "createdBy": "4214932441cb21eebdb396bfe34a8340"
  },
  "subListId": "610ffd8c7374d6331a4178d8",
  "subTasks": [
    {
      "status": "pending",
      "text": "Ship v3",
      "shortId": "T4QMF",
      "createdAt": "2022-01-10T12:15:13.627Z",
      "updatedAt": "2022-01-10T12:19:50.379Z",
      "listPosition": 100000,
      "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49/task/7cec8c8604790b391221049f28d5ba40",
      "calendars": [
        "b2956627fe26a2c1e4b6d5202413f779"
      ],
      "id": "7cec8c8604790b391221049f28d5ba40",
      "list": {
        "id": "603449f6f107b67c63e8cee9",
        "name": "Product",
        "type": "group",
        "privacy": "private",
        "link": "https://app.workast.com/list/603449f6f107b67c63e8cee9",
        "subLists": [
          {
            "id": "603449f6f107b67c63e8cee8",
            "name": "To-do",
            "listPosition": 100000,
            "createdBy": "4214932441cb21eebdb396bfe34a8340"
          },
          {
            "id": "610ffd8c7374d6331a4178d8",
            "name": "In Progress",
            "listPosition": 700000,
            "createdBy": "4214932441cb21eebdb396bfe34a8340"
          }
        ]
      },
      "listId": "603449f6f107b67c63e8cee9",
      "parent": {
        "id": "3634dc043f0d415ec2d307284a3cfe69",
        "text": "Ship v3",
        "shortId": "T4GNY",
        "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49/task/3634dc043f0d415ec2d307284a3cfe69"
      },
      "assignedTo": [],
      "subscribers": [
        {
          "id": "b2956627fe26a2c1e4b6d5202413f779",
          "name": "Ada Lovelace",
          "userName": "ada",
          "email": "ada@example.com",
          "platformDetails": {
            "name": "slack",
            "imChannel": "D3F5RQA6B",
            "selfChannel": "D1LGYBCFQ",
            "userId": "U0JU26WRG",
            "teamId": "T0HBUA0TC"
          },
          "confirmed": true,
          "avatar": "https://cdn.workast.io/avatar.png",
          "costCenter": "5c1b92b0a57d2b342c1a610e"
        }
      ],
      "allDay": false,
      "createdBy": {
        "id": "b2956627fe26a2c1e4b6d5202413f779",
        "name": "Ada Lovelace",
        "userName": "ada",
        "email": "ada@example.com",
        "platformDetails": {
          "name": "slack",
          "imChannel": "D3F5RQA6B",
          "selfChannel": "D1LGYBCFQ",
          "userId": "U0JU26WRG",
          "teamId": "T0HBUA0TC"
        },
        "confirmed": true,
        "avatar": "https://cdn.workast.io/avatar.png",
        "costCenter": "5c1b92b0a57d2b342c1a610e"
      },
      "hasDescription": true,
      "numberOfComments": 0,
      "numberOfAttachments": 0,
      "subTasks": [],
      "isSubscribed": false,
      "taskStatus": {
        "id": "5c7184fa40721e2ed4175a6e",
        "label": "Open",
        "color": "#808080",
        "createdAt": "2019-02-23T17:38:02.928Z",
        "updatedAt": "2019-02-23T17:38:02.928Z"
      },
      "inHome": false,
      "fields": []
    }
  ],
  "attachments": [],
  "totalSubTasks": 1,
  "completedSubTasks": 0,
  "numberOfComments": 1,
  "lastComment": {
    "id": "686f7912fc2fef09733c6f58",
    "type": "comment",
    "value": "Ship v3",
    "status": "active",
    "createdAt": "2025-07-10T08:25:54.274Z",
    "updatedAt": "2025-07-10T08:25:54.274Z",
    "mentions": [
      {
        "id": "b2956627fe26a2c1e4b6d5202413f779",
        "name": "Ada Lovelace",
        "userName": "ada",
        "email": "ada@example.com",
        "platformDetails": {
          "name": "slack",
          "imChannel": "D3F5RQA6B",
          "selfChannel": "D1LGYBCFQ",
          "userId": "U0JU26WRG",
          "teamId": "T0HBUA0TC"
        },
        "confirmed": true,
        "avatar": "https://cdn.workast.io/avatar.png",
        "costCenter": "5c1b92b0a57d2b342c1a610e"
      }
    ],
    "reactions": [],
    "actor": {
      "type": "User",
      "data": {
        "id": "4214932441cb21eebdb396bfe34a8340",
        "name": "Grace Hopper",
        "userName": "grace",
        "email": "grace@example.com",
        "platformDetails": {
          "name": "slack",
          "imChannel": "D3EEXS3J6",
          "selfChannel": "D1HN843U3",
          "userId": "U0HBQESA1",
          "teamId": "T0HBUA0TC"
        },
        "confirmed": true,
        "avatar": "https://cdn.workast.io/avatar.png",
        "costCenter": "5c1b92b0a57d2b342c1a610e"
      }
    }
  },
  "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49/task/3634dc043f0d415ec2d307284a3cfe69",
  "dependencies": [],
  "milestones": [],
  "inHome": false,
  "fields": [
    {
      "id": "620120d5106d941d2ac206c7",
      "name": "Priority",
      "description": "Ship v3",
      "type": "options",
      "useAsTaskColor": false,
      "options": [
        {
          "id": "620120d5106d941d2ac206c8",
          "name": "Yes",
          "color": "#2ef00d"
        },
        {
          "id": "620120d5106d941d2ac206c9",
          "name": "No",
          "color": "#ee0551"
        }
      ],
      "value": ""
    }
  ],
  "calendars": [
    "b2956627fe26a2c1e4b6d5202413f779"
  ]
};

export const taskActivities: TaskActivities = {
  "activities": [
    {
      "id": "61dc22bee45fbc0e26ca342d",
      "type": "task_created",
      "createdAt": "2022-01-10T12:12:46.500Z",
      "updatedAt": "2022-01-10T12:12:46.500Z",
      "mentions": [],
      "actor": {
        "type": "User",
        "data": {
          "id": "b2956627fe26a2c1e4b6d5202413f779",
          "name": "Ada Lovelace",
          "userName": "ada",
          "email": "ada@example.com",
          "platformDetails": {
            "name": "slack",
            "imChannel": "D3F5RQA6B",
            "selfChannel": "D1LGYBCFQ",
            "userId": "U0JU26WRG",
            "teamId": "T0HBUA0TC"
          },
          "confirmed": true,
          "avatar": "https://cdn.workast.io/avatar.png",
          "costCenter": "5c1b92b0a57d2b342c1a610e"
        }
      },
      "userFriendlyContent": {
        "task": {
          "id": "3634dc043f0d415ec2d307284a3cfe69",
          "shortId": "T4GNY",
          "status": "pending",
          "subscribers": [
            "b2956627fe26a2c1e4b6d5202413f779",
            "4214932441cb21eebdb396bfe34a8340"
          ],
          "calendars": [
            "b2956627fe26a2c1e4b6d5202413f779"
          ],
          "text": "Ship v3",
          "description": "Ship v3",
          "subListId": "610ffd8c7374d6331a4178d8",
          "listId": "603449f6f107b67c63e8cee9",
          "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49/task/3634dc043f0d415ec2d307284a3cfe69",
          "allDay": false,
          "createdBy": {
            "id": "b2956627fe26a2c1e4b6d5202413f779",
            "createdAt": "2016-12-28T22:19:45.715Z",
            "name": "Ada Lovelace",
            "userName": "ada",
            "platformDetails": {
              "name": "slack",
              "imChannel": "D3F5RQA6B",
              "selfChannel": "D1LGYBCFQ",
              "userId": "U0JU26WRG",
              "teamId": "T0HBUA0TC"
            },
            "timezone": "Australia/Canberra",
            "email": "ada@example.com",
            "lastActive": "2025-07-10T01:22:15.814Z",
            "role": "admin",
            "status": "active",
            "confirmed": true,
            "profile": {},
            "avatar": "https://cdn.workast.io/avatar.png",
            "costCenter": "5c1b92b0a57d2b342c1a610e"
          },
          "assignedTo": [
            {
              "id": "b2956627fe26a2c1e4b6d5202413f779",
              "createdAt": "2016-12-28T22:19:45.715Z",
              "name": "Ada Lovelace",
              "userName": "ada",
              "platformDetails": {
                "name": "slack",
                "imChannel": "D3F5RQA6B",
                "selfChannel": "D1LGYBCFQ",
                "userId": "U0JU26WRG",
                "teamId": "T0HBUA0TC"
              },
              "timezone": "Australia/Canberra",
              "email": "ada@example.com",
              "lastActive": "2025-07-10T01:22:15.814Z",
              "role": "admin",
              "status": "active",
              "confirmed": true,
              "profile": {},
              "avatar": "https://cdn.workast.io/avatar.png",
              "costCenter": "5c1b92b0a57d2b342c1a610e"
            }
          ]
        },
        "list": {
          "id": "603449f6f107b67c63e8cee9",
          "name": "Product",
          "link": "https://app.workast.com/list/603449f6f107b67c63e8cee9",
          "subLists": [
            {
              "id": "603449f6f107b67c63e8cee8",
              "name": "To-do",
              "listPosition": 100000,
              "createdBy": "4214932441cb21eebdb396bfe34a8340"
            },
            {
              "id": "610ffd8c7374d6331a4178d8",
              "name": "In Progress",
              "listPosition": 700000,
              "createdBy": "4214932441cb21eebdb396bfe34a8340"
            }
          ],
          "platformDetails": {
            "name": "slack",
            "channelId": "G01NLRJ053L",
            "channelName": "engineering",
            "type": "group",
            "teamId": "T0HBUA0TC"
          }
        },
        "actor": {
          "type": "User",
          "id": {
            "id": "b2956627fe26a2c1e4b6d5202413f779",
            "name": "Ada Lovelace",
            "userName": "ada",
            "email": "ada@example.com",
            "platformDetails": {
              "name": "slack",
              "imChannel": "D3F5RQA6B",
              "selfChannel": "D1LGYBCFQ",
              "userId": "U0JU26WRG",
              "teamId": "T0HBUA0TC"
            },
            "confirmed": true,
            "avatar": "https://cdn.workast.io/avatar.png",
            "costCenter": "5c1b92b0a57d2b342c1a610e"
          }
        },
        "message": "{{actor}} created the task {{task}}"
      }
    }
  ],
  "total": 17
};

export const taskBulkUpdateResult: TaskBulkUpdateResult = {
  "modified": [
    "3634dc043f0d415ec2d307284a3cfe69"
  ],
  "error": []
};

export const tokenDetails: TokenDetails = {
  "app": {
    "id": "5d9a6b09269e415d36380d23",
    "name": "Example App"
  },
  "user": {
    "id": "4214932441cb21eebdb396bfe34a8340",
    "name": "Grace Hopper"
  },
  "team": {
    "id": "ca19601b6bb816ca95386698b3385d49",
    "name": "Example Team"
  }
};

export const user: User = {
  "id": "4214932441cb21eebdb396bfe34a8340",
  "virtualId": "c2xhY2svL1QwSEJVQTBUQzpVMEhCUUVTQTE=",
  "name": "Grace Hopper",
  "userName": "grace",
  "avatar": "https://cdn.workast.io/avatar.png"
};

export const userDetail: UserDetail = {
  "id": "4214932441cb21eebdb396bfe34a8340",
  "createdAt": "2017-04-14T02:14:44.247Z",
  "name": "Grace Hopper",
  "userName": "grace",
  "platformDetails": {
    "name": "slack",
    "imChannel": "D3EEXS3J6",
    "selfChannel": "D1HN843U3",
    "userId": "U0HBQESA1",
    "teamId": "T0HBUA0TC"
  },
  "timezone": "Australia/Canberra",
  "email": "grace@example.com",
  "lastActive": "2026-08-18T11:29:00.207Z",
  "role": "admin",
  "status": "active",
  "confirmed": true,
  "profile": {},
  "avatar": "https://cdn.workast.io/avatar.png",
  "costCenter": "5c1b92b0a57d2b342c1a610e"
};

export const userDetailWithTeam: UserDetailWithTeam = {
  "id": "4214932441cb21eebdb396bfe34a8340",
  "createdAt": "2017-04-14T02:14:44.247Z",
  "name": "Grace Hopper",
  "userName": "grace",
  "platformDetails": {
    "name": "slack",
    "imChannel": "D3EEXS3J6",
    "selfChannel": "D1HN843U3",
    "userId": "U0HBQESA1",
    "teamId": "T0HBUA0TC"
  },
  "timezone": "Australia/Canberra",
  "email": "grace@example.com",
  "lastActive": "2026-08-18T11:29:00.207Z",
  "role": "admin",
  "status": "active",
  "confirmed": true,
  "profile": {},
  "avatar": "https://cdn.workast.io/avatar.png",
  "costCenter": "5c1b92b0a57d2b342c1a610e",
  "team": {
    "id": "ca19601b6bb816ca95386698b3385d49",
    "name": "Example Team",
    "url": "https://app.workast.com",
    "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49",
    "domain": "example",
    "totalTasks": 54822,
    "status": "active",
    "createdAt": "2018-05-22T14:04:01.652Z",
    "betaTester": true,
    "platformDetails": {
      "name": "slack",
      "teamId": "T0HBUA0TC",
      "url": "https://example.slack.com/",
      "emailDomain": "example.com",
      "teamSize": 76
    },
    "icon": "https://cdn.workast.io/list-avatar.png"
  }
};

export const userResource: UserResource = {
  "id": "4214932441cb21eebdb396bfe34a8340",
  "name": "Grace Hopper",
  "email": "grace@example.com",
  "userName": "grace",
  "platformDetails": {
    "name": "slack",
    "imChannel": "D3EEXS3J6",
    "selfChannel": "D1HN843U3",
    "userId": "U0HBQESA1",
    "teamId": "T0HBUA0TC"
  },
  "role": "admin",
  "confirmed": true,
  "avatar": "https://cdn.workast.io/avatar.png",
  "personalListId": "5937861aa2470108bbf72e1d",
  "team": {
    "id": "ca19601b6bb816ca95386698b3385d49",
    "name": "Example Team",
    "url": "https://app.workast.com",
    "link": "https://open.workast.app/ca19601b6bb816ca95386698b3385d49",
    "domain": "example",
    "totalTasks": 54822,
    "status": "active",
    "createdAt": "2018-05-22T14:04:01.652Z",
    "betaTester": true,
    "platformDetails": {
      "name": "slack",
      "teamId": "T0HBUA0TC",
      "url": "https://example.slack.com/",
      "emailDomain": "example.com",
      "teamSize": 76
    },
    "icon": "https://cdn.workast.io/list-avatar.png",
    "activeUsers": 7
  },
  "organization": {
    "id": "5c1b92b0a57d2b342c1a610d",
    "name": "Example Organization",
    "defaultCostCenter": "5c1b92b0a57d2b342c1a610e"
  },
  "costCenter": {
    "id": "5c1b92b0a57d2b342c1a610e",
    "createdAt": "2018-12-20T13:01:36.566Z",
    "updatedAt": "2019-01-10T14:56:47.968Z",
    "name": "Default",
    "account": "premium",
    "createdBy": "c51a9c1a2ddfbcefa7abf74036e0c616",
    "product": {
      "id": "5ddfe4b458ddf740a5393ae9",
      "createdAt": "2019-11-28T15:16:04.653Z",
      "updatedAt": "2020-07-30T14:55:46.510Z",
      "name": "Professional",
      "default": false,
      "isPaid": true,
      "features": {
        "createSubtasks": true,
        "createPrivateSpaces": true,
        "createLists": true,
        "createTags": true,
        "importTemplates": true,
        "createTemplates": true,
        "createSearches": true,
        "createTaskStatus": true,
        "createGuestAccounts": true,
        "createTaskDependencies": true,
        "storageLimit": 5368709120,
        "createMilestones": true,
        "accessMeetings": true,
        "calendarSync": true,
        "downloadSearch": true,
        "createSpaces": true,
        "appLogin": true,
        "createFields": true,
        "timelineView": true,
        "aiWorkflows": true,
        "notetakerMinutesPerMonth": 600
      },
      "trialling": false,
      "currentPlan": {
        "id": "5ddfe4b458ddf740a5393aea",
        "term": "annual",
        "price": 9.95,
        "flatFee": false
      }
    },
    "storage": {
      "used": 2315908683,
      "total": 37580963840,
      "usedPercentage": 6.16,
      "freePercentage": 93.84
    },
    "isDefault": true,
    "activeUsers": 7
  },
  "calendars": [],
  "timezone": "Australia/Canberra",
  "reminders": {
    "channels": {
      "slack": true,
      "email": false
    },
    "days": [
      1,
      2,
      3,
      4,
      5
    ],
    "hour": 9,
    "hourUTC": 23,
    "taskAssignedToOthers": false,
    "taskDueInTheFutureDays": 0
  },
  "notifications": {
    "assignedToTasks": true,
    "completedTasks": true,
    "appAnnouncements": true,
    "taskReminderMinutes": 30
  },
  "dateSettings": {
    "startOfWeek": "monday",
    "timeFormat": "HH",
    "dateFormat": "M/D/Y"
  },
  "myTasksSearchSettings": {
    "excludeAssignToOthers": true,
    "excludedLists": [
      {
        "id": "5937861aa2470108bbf72e1d",
        "name": "Personal tasks",
        "type": "personal",
        "privacy": "private"
      },
      {
        "id": "59daaf15c7d6260e7f470356",
        "name": "Product",
        "type": "group",
        "privacy": "team"
      }
    ]
  },
  "profile": {},
  "storage": {
    "used": 627473089,
    "total": 5368709120,
    "usedPercentage": 11.69,
    "freePercentage": 88.31
  }
};

export const workflow: Workflow = {
  "id": "673b14ef1231f8099d5c96a4",
  "trigger": {
    "name": "event",
    "value": "task_created"
  },
  "prompt": "Ship v3",
  "lists": [
    {
      "id": "673b0b7b1231f8099d5ba067",
      "type": "group",
      "status": "archived",
      "privacy": "team",
      "link": "https://app.workast.com/list/673b0b7b1231f8099d5ba067",
      "name": "Engineering"
    }
  ],
  "status": "active"
};

export const workflowDetail: WorkflowDetail = {
  "id": "673b14ef1231f8099d5c96a4",
  "trigger": {
    "name": "event",
    "value": "task_created"
  },
  "prompt": "Ship v3",
  "lists": [
    {
      "id": "673b0b7b1231f8099d5ba067",
      "type": "group",
      "status": "archived",
      "privacy": "team",
      "link": "https://app.workast.com/list/673b0b7b1231f8099d5ba067",
      "name": "Engineering"
    }
  ],
  "status": "active",
  "runs": [
    {
      "id": "673bffe012f608759e4bebca",
      "result": "Ship v3",
      "activity": {
        "id": "673bffdc77ac5a0996dc537d",
        "task": {
          "id": "e1bb3fcad526680b6e7387e988fea1d9",
          "text": "Ship v3",
          "shortId": "T31UJ",
          "link": "https://app.workast.com/task/e1bb3fcad526680b6e7387e988fea1d9"
        }
      },
      "createdAt": "2024-11-19T03:02:56.261Z"
    }
  ],
  "totalRuns": 4
};

export const workflows: Workflows = {
  "workflows": [
    {
      "id": "673b14ef1231f8099d5c96a4",
      "trigger": {
        "name": "event",
        "value": "task_created"
      },
      "prompt": "Ship v3",
      "lists": [
        {
          "id": "673b0b7b1231f8099d5ba067",
          "type": "group",
          "status": "archived",
          "privacy": "team",
          "link": "https://app.workast.com/list/673b0b7b1231f8099d5ba067",
          "name": "Engineering"
        }
      ],
      "status": "active"
    }
  ],
  "total": 11
};
