/**
 * Generate Public SDK types from swagger.
 *
 * Usage:
 *   npm run generate:types -- --swagger ../workast-api/swagger.yaml
 *   node scripts/generate-types.mjs --swagger <path> --out-dir <dir>
 *
 * Default swagger path (if --swagger is omitted): ../workast-api/swagger.yaml
 * relative to the SDK repo root.
 * Default --out-dir: src/types
 *
 * Pipeline: openapi-format (Public filter) → tmp filtered spec →
 * openapi-typescript → <out-dir>/openapi.d.ts + <out-dir>/generated.ts.
 */
import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const require = createRequire(import.meta.url);
const { parseFile, openapiFilter, writeFile: writeSpec } = require('openapi-format');

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');
const DEFAULT_SWAGGER = path.resolve(REPO_ROOT, '../workast-api/swagger.yaml');
const FILTER_FILE = path.join(__dirname, 'public-filter.yaml');
const DEFAULT_OUT_DIR = path.join(REPO_ROOT, 'src/types');

const HTTP_METHODS = ['get', 'put', 'post', 'delete', 'patch', 'head', 'options', 'trace'];

/**
 * Existing SDK query export names → Public swagger path + method.
 * Prefer these over names derived from operationId (e.g. ListSearchQuery, not GetListsQuery).
 */
const QUERY_ALIAS_MAP = {
  'GET /list': 'ListSearchQuery',
  'GET /list/sublists': 'SubListSearchQuery',
  'GET /field': 'CustomFieldSearchQuery',
  'GET /tag': 'TagSearchQuery',
  'GET /task/{taskId}/activity': 'TaskActivitySearchQuery',
  'GET /calendar/events': 'CalendarEventSearchQuery',
  'GET /attachment/{attachmentId}/file': 'AttachmentFileUrlQuery',
  'GET /meeting': 'MeetingSearchQuery',
  'GET /search': 'SearchFindQuery',
  'GET /search/{searchId}': 'SearchRetrieveQuery',
  'GET /workflow': 'WorkflowSearchQuery',
  'GET /user': 'UserSearchQuery',
  'GET /user/email/{email}': 'UserByEmailQuery',
  'GET /note': 'NoteSearchQuery',
  'GET /notification': 'NotificationSearchQuery',
};

/**
 * Unmapped Public operations with query params are aliased as:
 *   PascalCase(operationId) + "Query"  (no double "Query" suffix)
 * If operationId is missing:
 *   PascalCase(method) + PascalCase(path segments without {}) + "Query"
 *   e.g. GET /foo/{id}/bar → GetFooIdBarQuery
 * Schema component names win on collision; a mapped SDK name is not replaced.
 */

function parseFlagValue(argv, flag, usage) {
  const index = argv.indexOf(flag);
  if (index === -1) {
    return undefined;
  }
  const value = argv[index + 1];
  if (!value || value.startsWith('-')) {
    throw new Error(`Missing value for ${flag}. ${usage}`);
  }
  return path.resolve(process.cwd(), value);
}

function parseSwaggerArg(argv) {
  return parseFlagValue(
    argv,
    '--swagger',
    'Usage: npm run generate:types -- --swagger <path>',
  ) ?? DEFAULT_SWAGGER;
}

function parseOutDirArg(argv) {
  return parseFlagValue(
    argv,
    '--out-dir',
    'Usage: node scripts/generate-types.mjs --out-dir <dir>',
  ) ?? DEFAULT_OUT_DIR;
}

function fileHeader(hash) {
  return `/**
 * This file was generated by scripts/generate-types.mjs. Do not edit.
 * Source swagger SHA-256: ${hash}
 */
`;
}

function isIdentifier(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}

function pascalCase(value) {
  return String(value)
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function queryAliasFromOperation(method, specPath, operationId) {
  if (operationId) {
    const base = pascalCase(operationId);
    return base.endsWith('Query') ? base : `${base}Query`;
  }
  const pathParts = specPath
    .replace(/[{}]/g, '')
    .split('/')
    .filter(Boolean)
    .map(pascalCase)
    .join('');
  return `${pascalCase(method)}${pathParts}Query`;
}

function resolveParam(param, spec) {
  if (!param || typeof param !== 'object' || !param.$ref) {
    return param;
  }
  const name = String(param.$ref).split('/').pop();
  return spec.components?.parameters?.[name];
}

function hasQueryParams(operation, pathItem, spec) {
  const params = [...(pathItem.parameters ?? []), ...(operation.parameters ?? [])];
  return params.some((param) => resolveParam(param, spec)?.in === 'query');
}

function collectQueryOperations(spec) {
  const found = [];
  for (const [specPath, pathItem] of Object.entries(spec.paths ?? {})) {
    if (!pathItem || typeof pathItem !== 'object') {
      continue;
    }
    for (const method of HTTP_METHODS) {
      const operation = pathItem[method];
      if (!operation || typeof operation !== 'object') {
        continue;
      }
      if (hasQueryParams(operation, pathItem, spec)) {
        found.push({
          path: specPath,
          method,
          operationId: operation.operationId,
        });
      }
    }
  }
  return found;
}

function schemaNames(spec) {
  return Object.keys(spec.components?.schemas ?? {}).filter(isIdentifier).sort();
}

function emitSchemaAliases(names) {
  return names.map((name) => `export type ${name} = components["schemas"][${JSON.stringify(name)}];`);
}

function emitQueryAliases(spec, usedNames) {
  const used = new Set(usedNames);
  const mapped = [];
  const derived = [];

  for (const op of collectQueryOperations(spec)) {
    const key = `${op.method.toUpperCase()} ${op.path}`;
    const mappedName = QUERY_ALIAS_MAP[key];
    if (mappedName) {
      if (used.has(mappedName)) {
        continue;
      }
      used.add(mappedName);
      mapped.push({ name: mappedName, path: op.path, method: op.method });
      continue;
    }

    let name = queryAliasFromOperation(op.method, op.path, op.operationId);
    if (!isIdentifier(name) || used.has(name)) {
      continue;
    }
    used.add(name);
    derived.push({ name, path: op.path, method: op.method });
  }

  mapped.sort((a, b) => a.name.localeCompare(b.name));
  derived.sort((a, b) => a.name.localeCompare(b.name));

  return [...mapped, ...derived].map(
    (alias) =>
      `export type ${alias.name} = NonNullable<paths[${JSON.stringify(alias.path)}][${JSON.stringify(alias.method)}]["parameters"]["query"]>;`,
  );
}

async function main() {
  const argv = process.argv.slice(2);
  const swaggerPath = parseSwaggerArg(argv);
  const outDir = parseOutDirArg(argv);
  const openapiDts = path.join(outDir, 'openapi.d.ts');
  const generatedTs = path.join(outDir, 'generated.ts');
  const sourceBytes = await readFile(swaggerPath);
  const hash = createHash('sha256').update(sourceBytes).digest('hex');

  const spec = await parseFile(swaggerPath);
  const filterSet = await parseFile(FILTER_FILE);
  const { data: filtered } = await openapiFilter(spec, { filterSet });

  const filteredDir = await mkdtemp(path.join(tmpdir(), 'workast-sdk-types-'));
  const filteredPath = path.join(filteredDir, 'public-swagger.json');
  await writeSpec(filteredPath, filtered, { format: 'json' });

  const ast = await openapiTS(pathToFileURL(filteredPath));
  const header = fileHeader(hash);
  await mkdir(outDir, { recursive: true });
  await writeFile(openapiDts, `${header}\n${astToString(ast)}`);

  const names = schemaNames(filtered);
  const schemaLines = emitSchemaAliases(names);
  const queryLines = emitQueryAliases(filtered, names);
  const generated = [
    header,
    `import type { components, paths } from './openapi.js';`,
    '',
    ...schemaLines,
    ...(schemaLines.length && queryLines.length ? [''] : []),
    ...queryLines,
    '',
  ].join('\n');
  await writeFile(generatedTs, generated);

  process.stdout.write(`Wrote ${path.relative(REPO_ROOT, openapiDts)} and ${path.relative(REPO_ROOT, generatedTs)}\n`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
